FROM ruby:3.4.7
RUN apt-get update -qq && \
    apt-get install -y build-essential nodejs npm postgresql-client curl gnupg2 libyaml-dev

RUN corepack enable && corepack prepare yarn@4.12.0 --activate

WORKDIR /la_colmena
COPY Gemfile /la_colmena/Gemfile
COPY Gemfile.lock /la_colmena/Gemfile.lock
RUN bundle install

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Configure the main process to run when running the image
CMD ["rails", "server", "-b", "0.0.0.0"]


